runmode: debug                 # 开发模式, debug, release, test
addr: :8081                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数

gormlog: true
db:
  username: root
  password: root
  addr: 127.0.0.1:3306
  name: db_apiserver
